# -*- coding: utf-8 -*-
#
# Generated by the OpenERP plugin for Dia !
#
import fundraising
import attribution
import gift
import solicitation
import partner
import wizard
import report
import thanks
import attestation